-- Inventory stock count sync from Fouleh's inventory xlsx (3/30 snapshot)
-- 196 variant stock updates
-- Generated from docs/STANCIL SERVICES INVENTORY COUNT .xlsx

UPDATE product_variants SET stock_quantity = 0 WHERE id = 141; -- Short Sleeve T-Shirt / S / white (was 0)
UPDATE product_variants SET stock_quantity = 4 WHERE id = 142; -- Short Sleeve T-Shirt / M / white (was 4)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 143; -- Short Sleeve T-Shirt / L / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 144; -- Short Sleeve T-Shirt / XL / white (was 0)
UPDATE product_variants SET stock_quantity = 4 WHERE id = 145; -- Short Sleeve T-Shirt / 2XL / white (was 4)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 146; -- Short Sleeve T-Shirt / 3XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 147; -- Short Sleeve T-Shirt / 4XL / white (was 0)
UPDATE product_variants SET stock_quantity = 50 WHERE id = 53; -- Short Sleeve T-Shirt / S / safety green (was 50)
UPDATE product_variants SET stock_quantity = 49 WHERE id = 54; -- Short Sleeve T-Shirt / M / safety green (was 49)
UPDATE product_variants SET stock_quantity = 40 WHERE id = 55; -- Short Sleeve T-Shirt / L / safety green (was 40)
UPDATE product_variants SET stock_quantity = 12 WHERE id = 56; -- Short Sleeve T-Shirt / XL / safety green (was 12)
UPDATE product_variants SET stock_quantity = 29 WHERE id = 57; -- Short Sleeve T-Shirt / 2XL / safety green (was 29)
UPDATE product_variants SET stock_quantity = 17 WHERE id = 58; -- Short Sleeve T-Shirt / 3XL / safety green (was 17)
UPDATE product_variants SET stock_quantity = 41 WHERE id = 59; -- Short Sleeve T-Shirt / 4XL / safety green (was 41)
UPDATE product_variants SET stock_quantity = 76 WHERE id = 46; -- Short Sleeve T-Shirt / S / grey (was 76)
UPDATE product_variants SET stock_quantity = 72 WHERE id = 47; -- Short Sleeve T-Shirt / M / grey (was 72)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 48; -- Short Sleeve T-Shirt / L / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 49; -- Short Sleeve T-Shirt / XL / grey (was 0)
UPDATE product_variants SET stock_quantity = 29 WHERE id = 50; -- Short Sleeve T-Shirt / 2XL / grey (was 29)
UPDATE product_variants SET stock_quantity = 30 WHERE id = 51; -- Short Sleeve T-Shirt / 3XL / grey (was 30)
UPDATE product_variants SET stock_quantity = 35 WHERE id = 52; -- Short Sleeve T-Shirt / 4XL / grey (was 35)
UPDATE product_variants SET stock_quantity = 2 WHERE id = 148; -- Long Sleeve T-Shirt / S / white (was 2)
UPDATE product_variants SET stock_quantity = 3 WHERE id = 149; -- Long Sleeve T-Shirt / M / white (was 3)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 150; -- Long Sleeve T-Shirt / L / white (was 7)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 151; -- Long Sleeve T-Shirt / XL / white (was 7)
UPDATE product_variants SET stock_quantity = 9 WHERE id = 152; -- Long Sleeve T-Shirt / 2XL / white (was 9)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 153; -- Long Sleeve T-Shirt / 3XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 154; -- Long Sleeve T-Shirt / 4XL / white (was 0)
UPDATE product_variants SET stock_quantity = 40 WHERE id = 61; -- Long Sleeve T-Shirt / S / safety green (was 40)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 63; -- Long Sleeve T-Shirt / M / safety green (was 20)
UPDATE product_variants SET stock_quantity = 36 WHERE id = 65; -- Long Sleeve T-Shirt / L / safety green (was 36)
UPDATE product_variants SET stock_quantity = 41 WHERE id = 67; -- Long Sleeve T-Shirt / XL / safety green (was 41)
UPDATE product_variants SET stock_quantity = 40 WHERE id = 69; -- Long Sleeve T-Shirt / 2XL / safety green (was 40)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 71; -- Long Sleeve T-Shirt / 3XL / safety green (was 20)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 73; -- Long Sleeve T-Shirt / 4XL / safety green (was 18)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 60; -- Long Sleeve T-Shirt / S / grey (was 18)
UPDATE product_variants SET stock_quantity = 42 WHERE id = 62; -- Long Sleeve T-Shirt / M / grey (was 42)
UPDATE product_variants SET stock_quantity = 4 WHERE id = 64; -- Long Sleeve T-Shirt / L / grey (was 4)
UPDATE product_variants SET stock_quantity = 48 WHERE id = 66; -- Long Sleeve T-Shirt / XL / grey (was 48)
UPDATE product_variants SET stock_quantity = 61 WHERE id = 68; -- Long Sleeve T-Shirt / 2XL / grey (was 61)
UPDATE product_variants SET stock_quantity = 21 WHERE id = 70; -- Long Sleeve T-Shirt / 3XL / grey (was 21)
UPDATE product_variants SET stock_quantity = 19 WHERE id = 72; -- Long Sleeve T-Shirt / 4XL / grey (was 19)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 75; -- Short Sleeve Dry Fit T-Shirt / S / safety green (was 18)
UPDATE product_variants SET stock_quantity = 22 WHERE id = 77; -- Short Sleeve Dry Fit T-Shirt / M / safety green (was 22)
UPDATE product_variants SET stock_quantity = 15 WHERE id = 79; -- Short Sleeve Dry Fit T-Shirt / L / safety green (was 15)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 81; -- Short Sleeve Dry Fit T-Shirt / XL / safety green (was 18)
UPDATE product_variants SET stock_quantity = 27 WHERE id = 83; -- Short Sleeve Dry Fit T-Shirt / 2XL / safety green (was 27)
UPDATE product_variants SET stock_quantity = 22 WHERE id = 85; -- Short Sleeve Dry Fit T-Shirt / 3XL / safety green (was 22)
UPDATE product_variants SET stock_quantity = 25 WHERE id = 87; -- Short Sleeve Dry Fit T-Shirt / 4XL / safety green (was 25)
UPDATE product_variants SET stock_quantity = 13 WHERE id = 74; -- Short Sleeve Dry Fit T-Shirt / S / blue (was 13)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 76; -- Short Sleeve Dry Fit T-Shirt / M / blue (was 18)
UPDATE product_variants SET stock_quantity = 13 WHERE id = 78; -- Short Sleeve Dry Fit T-Shirt / L / blue (was 13)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 80; -- Short Sleeve Dry Fit T-Shirt / XL / blue (was 20)
UPDATE product_variants SET stock_quantity = 33 WHERE id = 82; -- Short Sleeve Dry Fit T-Shirt / 2XL / blue (was 33)
UPDATE product_variants SET stock_quantity = 27 WHERE id = 84; -- Short Sleeve Dry Fit T-Shirt / 3XL / blue (was 27)
UPDATE product_variants SET stock_quantity = 24 WHERE id = 86; -- Short Sleeve Dry Fit T-Shirt / 4XL / blue (was 24)
UPDATE product_variants SET stock_quantity = 12 WHERE id = 89; -- Long Sleeve Dry Fit T-Shirt / S / safety green (was 12)
UPDATE product_variants SET stock_quantity = 8 WHERE id = 91; -- Long Sleeve Dry Fit T-Shirt / M / safety green (was 8)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 93; -- Long Sleeve Dry Fit T-Shirt / L / safety green (was 7)
UPDATE product_variants SET stock_quantity = 11 WHERE id = 95; -- Long Sleeve Dry Fit T-Shirt / XL / safety green (was 11)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 97; -- Long Sleeve Dry Fit T-Shirt / 2XL / safety green (was 18)
UPDATE product_variants SET stock_quantity = 19 WHERE id = 99; -- Long Sleeve Dry Fit T-Shirt / 3XL / safety green (was 19)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 101; -- Long Sleeve Dry Fit T-Shirt / 4XL / safety green (was 20)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 88; -- Long Sleeve Dry Fit T-Shirt / S / blue (was 20)
UPDATE product_variants SET stock_quantity = 23 WHERE id = 90; -- Long Sleeve Dry Fit T-Shirt / M / blue (was 23)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 92; -- Long Sleeve Dry Fit T-Shirt / L / blue (was 10)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 94; -- Long Sleeve Dry Fit T-Shirt / XL / blue (was 7)
UPDATE product_variants SET stock_quantity = 40 WHERE id = 96; -- Long Sleeve Dry Fit T-Shirt / 2XL / blue (was 40)
UPDATE product_variants SET stock_quantity = 27 WHERE id = 98; -- Long Sleeve Dry Fit T-Shirt / 3XL / blue (was 27)
UPDATE product_variants SET stock_quantity = 30 WHERE id = 100; -- Long Sleeve Dry Fit T-Shirt / 4XL / blue (was 30)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 103; -- Crew Neck Sweatshirt / S / safety green (was 10)
UPDATE product_variants SET stock_quantity = 22 WHERE id = 105; -- Crew Neck Sweatshirt / M / safety green (was 22)
UPDATE product_variants SET stock_quantity = 17 WHERE id = 107; -- Crew Neck Sweatshirt / L / safety green (was 17)
UPDATE product_variants SET stock_quantity = 20 WHERE id = 109; -- Crew Neck Sweatshirt / XL / safety green (was 20)
UPDATE product_variants SET stock_quantity = 18 WHERE id = 111; -- Crew Neck Sweatshirt / 2XL / safety green (was 18)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 113; -- Crew Neck Sweatshirt / 3XL / safety green (was 10)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 115; -- Crew Neck Sweatshirt / 4XL / safety green (was 10)
UPDATE product_variants SET stock_quantity = 8 WHERE id = 102; -- Crew Neck Sweatshirt / S / grey (was 8)
UPDATE product_variants SET stock_quantity = 8 WHERE id = 104; -- Crew Neck Sweatshirt / M / grey (was 8)
UPDATE product_variants SET stock_quantity = 9 WHERE id = 106; -- Crew Neck Sweatshirt / L / grey (was 9)
UPDATE product_variants SET stock_quantity = 13 WHERE id = 108; -- Crew Neck Sweatshirt / XL / grey (was 13)
UPDATE product_variants SET stock_quantity = 11 WHERE id = 110; -- Crew Neck Sweatshirt / 2XL / grey (was 9)
UPDATE product_variants SET stock_quantity = 11 WHERE id = 112; -- Crew Neck Sweatshirt / 3XL / grey (was 11)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 114; -- Crew Neck Sweatshirt / 4XL / grey (was 10)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 117; -- Hoodie / S / safety green (was 10)
UPDATE product_variants SET stock_quantity = 13 WHERE id = 119; -- Hoodie / M / safety green (was 13)
UPDATE product_variants SET stock_quantity = 12 WHERE id = 121; -- Hoodie / L / safety green (was 12)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 123; -- Hoodie / XL / safety green (was 0)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 125; -- Hoodie / 2XL / safety green (was 10)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 127; -- Hoodie / 3XL / safety green (was 7)
UPDATE product_variants SET stock_quantity = 11 WHERE id = 129; -- Hoodie / 4XL / safety green (was 11)
UPDATE product_variants SET stock_quantity = 8 WHERE id = 116; -- Hoodie / S / grey (was 8)
UPDATE product_variants SET stock_quantity = 5 WHERE id = 118; -- Hoodie / M / grey (was 5)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 120; -- Hoodie / L / grey (was 0)
UPDATE product_variants SET stock_quantity = 12 WHERE id = 122; -- Hoodie / XL / grey (was 12)
UPDATE product_variants SET stock_quantity = 2 WHERE id = 124; -- Hoodie / 2XL / grey (was 2)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 126; -- Hoodie / 3XL / grey (was 10)
UPDATE product_variants SET stock_quantity = 10 WHERE id = 128; -- Hoodie / 4XL / grey (was 10)
UPDATE product_variants SET stock_quantity = 875 WHERE id = 155; -- New Logo Lanyard / [singleton variant] (was 875)
UPDATE product_variants SET stock_quantity = 58 WHERE id = 4; -- Stancil Notebook / [singleton variant] (was 58)
UPDATE product_variants SET stock_quantity = 44 WHERE id = 316; -- Stancil Marmot Raincoat / L / grey (was 46)
UPDATE product_variants SET stock_quantity = 19 WHERE id = 317; -- Stancil Marmot Raincoat / XL / grey (was 19)
UPDATE product_variants SET stock_quantity = 5 WHERE id = 318; -- Stancil Marmot Raincoat / 2XL / grey (was 5)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 318; -- Stancil Marmot Raincoat / 2XL / grey (was 5)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 320; -- Stancil Marmot Raincoat / 4XL / blue [size-only match for xlsx color 'GREY'] (was 4)
UPDATE product_variants SET stock_quantity = 4 WHERE id = 320; -- Stancil Marmot Raincoat / 4XL / blue (was 4)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 264; -- Women's Polo Shirt (Stancil Logo) / S / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 288; -- Women's Polo Shirt (Stancil Logo) / M / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 283; -- Women's Polo Shirt (Stancil Logo) / L / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 284; -- Women's Polo Shirt (Stancil Logo) / XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 285; -- Women's Polo Shirt (Stancil Logo) / 2XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 286; -- Women's Polo Shirt (Stancil Logo) / 3XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 287; -- Women's Polo Shirt (Stancil Logo) / 4XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 261; -- Women's Polo Shirt (Stancil Logo) / S / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 265; -- Women's Polo Shirt (Stancil Logo) / M / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 266; -- Women's Polo Shirt (Stancil Logo) / L / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 267; -- Women's Polo Shirt (Stancil Logo) / XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 268; -- Women's Polo Shirt (Stancil Logo) / 2XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 269; -- Women's Polo Shirt (Stancil Logo) / 3XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 270; -- Women's Polo Shirt (Stancil Logo) / 4XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 262; -- Women's Polo Shirt (Stancil Logo) / S / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 271; -- Women's Polo Shirt (Stancil Logo) / M / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 272; -- Women's Polo Shirt (Stancil Logo) / L / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 273; -- Women's Polo Shirt (Stancil Logo) / XL / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 274; -- Women's Polo Shirt (Stancil Logo) / 2XL / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 275; -- Women's Polo Shirt (Stancil Logo) / 3XL / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 276; -- Women's Polo Shirt (Stancil Logo) / 4XL / grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 263; -- Women's Polo Shirt (Stancil Logo) / S / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 277; -- Women's Polo Shirt (Stancil Logo) / M / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 278; -- Women's Polo Shirt (Stancil Logo) / L / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 279; -- Women's Polo Shirt (Stancil Logo) / XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 280; -- Women's Polo Shirt (Stancil Logo) / 2XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 281; -- Women's Polo Shirt (Stancil Logo) / 3XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 282; -- Women's Polo Shirt (Stancil Logo) / 4XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 233; -- Men's Polo Shirt (Stancil Logo) / S / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 234; -- Men's Polo Shirt (Stancil Logo) / M / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 235; -- Men's Polo Shirt (Stancil Logo) / L / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 236; -- Men's Polo Shirt (Stancil Logo) / XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 237; -- Men's Polo Shirt (Stancil Logo) / 2XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 238; -- Men's Polo Shirt (Stancil Logo) / 3XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 239; -- Men's Polo Shirt (Stancil Logo) / 4XL / white (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 254; -- Men's Polo Shirt (Stancil Logo) / S / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 255; -- Men's Polo Shirt (Stancil Logo) / M / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 256; -- Men's Polo Shirt (Stancil Logo) / L / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 257; -- Men's Polo Shirt (Stancil Logo) / XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 258; -- Men's Polo Shirt (Stancil Logo) / 2XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 259; -- Men's Polo Shirt (Stancil Logo) / 3XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 260; -- Men's Polo Shirt (Stancil Logo) / 4XL / blue lake (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 247; -- Men's Polo Shirt (Stancil Logo) / S / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 248; -- Men's Polo Shirt (Stancil Logo) / M / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 249; -- Men's Polo Shirt (Stancil Logo) / L / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 250; -- Men's Polo Shirt (Stancil Logo) / XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 251; -- Men's Polo Shirt (Stancil Logo) / 2XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 252; -- Men's Polo Shirt (Stancil Logo) / 3XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 253; -- Men's Polo Shirt (Stancil Logo) / 4XL / royal blue (was 0)
UPDATE product_variants SET stock_quantity = 6 WHERE id = 199; -- Camo Long-Sleeve Dry Fit T-Shirts / S / camo (was 6)
UPDATE product_variants SET stock_quantity = 15 WHERE id = 200; -- Camo Long-Sleeve Dry Fit T-Shirts / M / camo (was 15)
UPDATE product_variants SET stock_quantity = 30 WHERE id = 201; -- Camo Long-Sleeve Dry Fit T-Shirts / L / camo (was 30)
UPDATE product_variants SET stock_quantity = 24 WHERE id = 202; -- Camo Long-Sleeve Dry Fit T-Shirts / XL / camo (was 24)
UPDATE product_variants SET stock_quantity = 16 WHERE id = 203; -- Camo Long-Sleeve Dry Fit T-Shirts / 2XL / camo (was 2)
UPDATE product_variants SET stock_quantity = 22 WHERE id = 204; -- Camo Long-Sleeve Dry Fit T-Shirts / 3XL / camo (was 22)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 205; -- Camo Long-Sleeve Dry Fit T-Shirts / 4XL / camo (was 7)
UPDATE product_variants SET stock_quantity = 6 WHERE id = 292; -- Camo Short-Sleeve Dry Fit T-Shirts / S / camo (was 6)
UPDATE product_variants SET stock_quantity = 15 WHERE id = 293; -- Camo Short-Sleeve Dry Fit T-Shirts / M / camo (was 15)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 294; -- Camo Short-Sleeve Dry Fit T-Shirts / L / camo (was 0)
UPDATE product_variants SET stock_quantity = 12 WHERE id = 295; -- Camo Short-Sleeve Dry Fit T-Shirts / XL / camo (was 12)
UPDATE product_variants SET stock_quantity = 3 WHERE id = 296; -- Camo Short-Sleeve Dry Fit T-Shirts / 2XL / camo (was 3)
UPDATE product_variants SET stock_quantity = 7 WHERE id = 297; -- Camo Short-Sleeve Dry Fit T-Shirts / 3XL / camo (was 7)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 298; -- Camo Short-Sleeve Dry Fit T-Shirts / 4XL / camo (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 16; -- Carhartt Winter Vest / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 6 WHERE id = 16; -- Carhartt Winter Vest / M / dark grey (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 16; -- Carhartt Winter Vest / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 16; -- Carhartt Winter Vest / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 16; -- Carhartt Winter Vest / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 16; -- Carhartt Winter Vest / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 43; -- Eddie Bauer Winter Vest / 3XL / dark grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 132; -- Eddie Bauer Winter Vest / 4XL / dark grey (was 0)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 303; -- Carhartt Winter Jacket / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 6 WHERE id = 303; -- Carhartt Winter Jacket / M / dark grey (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 303; -- Carhartt Winter Jacket / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 303; -- Carhartt Winter Jacket / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 303; -- Carhartt Winter Jacket / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 303; -- Carhartt Winter Jacket / [singleton variant] (was 6)
UPDATE product_variants SET stock_quantity = 2 WHERE id = 7; -- Milwaukee Jobsite Cooler / [singleton variant] (was 2)
UPDATE product_variants SET stock_quantity = 4 WHERE id = 27; -- Milwaukee Packout Cooler / [singleton variant] (was 4)
UPDATE product_variants SET stock_quantity = 19 WHERE id = 133; -- Carhartt Backpack / N/A / black (was 19)
UPDATE product_variants SET stock_quantity = 120 WHERE id = 300; -- Adjustable Hat (Commercial) / N/A / sandstone (was 120)
UPDATE product_variants SET stock_quantity = 84 WHERE id = 138; -- Adjustable Hat (Custom) / N/A / black (was 84)
UPDATE product_variants SET stock_quantity = 48 WHERE id = 299; -- Adjustable Hat (Coastal) / N/A / sandstone (was 48)
UPDATE product_variants SET stock_quantity = 108 WHERE id = 301; -- Adjustable Hat (New Residential) / N/A / sandstone (was 108)
UPDATE product_variants SET stock_quantity = 123 WHERE id = 210; -- Arctic Camo Hat / N/A / camo (was 120)
UPDATE product_variants SET stock_quantity = 48 WHERE id = 211; -- Trucker Hat / N/A / black (was 48)
UPDATE product_variants SET stock_quantity = 0 WHERE id = 212; -- Camo Debossed Hat / N/A / grey (was 24)
UPDATE product_variants SET stock_quantity = 3 WHERE id = 223; -- Carhartt Beanie / N/A / tan (was 3)
UPDATE product_variants SET stock_quantity = 8 WHERE id = 224; -- Carhartt Beanie / N/A / brown (was 8)
UPDATE product_variants SET stock_quantity = 1 WHERE id = 225; -- Carhartt Beanie / N/A / electric blue (was 1)
