-- Migration 0009: Seed 2026 credit eligibility from Jenny's roster.
--
-- Sets yearly_credit = 0 for 102 stancilservices.com profiles that did not
-- appear on the 2026 Employee Uniform Credit roster. Ineligible roles
-- (corporate, HR, IT, sales leadership, executives, etc.).
--
-- Idempotent: re-running is a no-op. Any future exceptions are expected
-- to be handled manually via /hub/store/employees/edit.

UPDATE profiles
SET yearly_credit = 0,
    updated_at = datetime('now')
WHERE email IN (
  'Alan.Caldwell@stancilservices.com',
  'Aleah.Holland@stancilservices.com',
  'Alex.Orosz@stancilservices.com',
  'Amber.Widenhouse@stancilservices.com',
  'Andrew.Szafranski@stancilservices.com',
  'Anjie.Hinson@stancilservices.com',
  'anthony.foster@stancilservices.com',
  'ashley.sullins@stancilservices.com',
  'Bailey.Jackson@stancilservices.com',
  'ben.perkton@stancilservices.com',
  'Ben.Russey@stancilservices.com',
  'bmangum1+storetest@gmail.com',
  'brian.mangum@stancilservices.com',
  'Brian.Scott@stancilservices.com',
  'bryan.thomas@stancilservices.com',
  'Carlos.Vergara@stancilservices.com',
  'christopher.hines@stancilservices.com',
  'craig.neal@stancilservices.com',
  'Crystal.Wallace@stancilservices.com',
  'Cynthia.Stubbs@stancilservices.com',
  'daniel.hdezguevara@gmail.com',
  'David.Jaimes@stancilservices.com',
  'Donny.Petty@stancilservices.com',
  'Doug.Jones@stancilservices.com',
  'Doug.LeRoux@stancilservices.com',
  'emily.messina@stancilservices.com',
  'escobar.enmanuel06@gmail.com',
  'fouleh.freitekh@stancilservices.com',
  'Gabe.Robledo@stancilservices.com',
  'Gissell.Flores@stancilservices.com',
  'greg.lipa@stancilservices.com',
  'hernandezjulio488@yahoo.com',
  'itzel.arreola@stancilservices.com',
  'Jacque.Sigerist@stancilservices.com',
  'James.Miller@stancilservices.com',
  'jamie.hoover@stancilservices.com',
  'Jenny.Burleson@stancilservices.com',
  'jenny.burleson@stancilservices.com',
  'Jessica.Phifer@stancilservices.com',
  'jesus.diaz@stancilpainting.com',
  'Jesus.Hernandez@stancilservices.com',
  'Jim.Arstark@stancilservices.com',
  'Jodi.Gaddy@stancilservices.com',
  'joe.galioto@stancilservices.com',
  'Joe.Villalta@stancilservices.com',
  'jon.thomas@stancilservices.com',
  'Jose.Alvarez@stancilservices.com',
  'kathleen.george@stancilservices.com',
  'Katie.Miller@stancilservices.com',
  'Kris.Gunther@stancilservices.com',
  'kris.gunther@stancilservices.com',
  'Kyle.Barrow@stancilservices.com',
  'Luis.Reyes@stancilservices.com',
  'Luis.Serrano@stancilservices.com',
  'lynnea.bogan@stancilservices.com',
  'Maggie.Bacon@stancilservices.com',
  'matt.mercer@stancilservices.com',
  'Matt.Moss@stancilservices.com',
  'melissa.nash@stancilservices.com',
  'Micah.Partlow@stancilservices.com',
  'micah.partlow@stancilservices.com',
  'michael.lee@stancilservices.com',
  'Miguel.Baker@stancilservices.com',
  'Mike.Davis@stancilservices.com',
  'morgan.whittington@stancilservices.com',
  'mycal.self@stancilservices.com',
  'nicholas.barbee@stancilservices.com',
  'Oscar.Luna@stancilservices.com',
  'Osvaldo.Macedo@stancilservices.com',
  'Paul.Ward@stancilservices.com',
  'rachel.valle@stancilservices.com',
  'ramos.perfecto@icloud.com',
  'Raul.Macias@stancilservices.com',
  'rayann.lefever@stancilservices.com',
  'rebecca.guiler@stancilservices.com',
  'robin.white@stancilservices.com',
  'rolandobladimir1814@icloud.com',
  'Rusty.Norris@stancilservices.com',
  'Salomon.Moctezuma@stancilservices.com',
  'scarlett.bowman@stancilservices.com',
  'Scott.Houser@stancilservices.com',
  'Scott.Stancil@stancilservices.com',
  'Scottie.Kimble@stancilservices.com',
  'Sebastian.Carrillo@stancilservices.com',
  'Stancil.BSA12@stancilservices.com',
  'stephanie.buono@stancilservices.com',
  'Steve.Herman@stancilservices.com',
  'steven.benesh@stancilservices.com',
  'sthephanie.castillo@stancilservices.com',
  'Sue.Bennett@stancilservices.com',
  'susie.rochin@stancilservices.com',
  'tara.white@stancilservices.com',
  'temp.employee2@stancilservices.com',
  'Terri.Simon@stancilservices.com',
  'Victoria.Reiner@stancilservices.com',
  'warehouse.leland@stancilservices.com',
  'warehouse.main@stancilservices.com',
  'Warehouse.South@stancilservices.com',
  'wayne.barker@stancilservices.com',
  'Wayne.Presley@stancilservices.com',
  'wilfred.medina@stancilservices.com',
  'Will.Jones@stancilservices.com'
);
