-- One-time backfill of first_name/last_name/display_name for profiles
-- where the names are still NULL. Source: HR roster CSV from Jenny
-- (site-stancil-new/docs/Store/names.csv). Names Title-Cased from
-- the all-caps source; emails matched case-insensitively.
--
-- 304 rows generated.

UPDATE profiles SET first_name = 'Francisco', last_name = 'Ramirez', display_name = 'Francisco Ramirez' WHERE LOWER(email) = 'dylanmatheoramirezquintanilla@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joan', last_name = 'Quintana', display_name = 'Joan Quintana' WHERE LOWER(email) = 'carlos.quintana@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Isau', last_name = 'Melgar Romero', display_name = 'Isau Melgar Romero' WHERE LOWER(email) = 'isaufea53@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cervando', last_name = 'Zapata Gongora', display_name = 'Cervando Zapata Gongora' WHERE LOWER(email) = 'mr1731760@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joshua', last_name = 'Williams', display_name = 'Joshua Williams' WHERE LOWER(email) = 'joshua.williams@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Yvan', last_name = 'Tellez', display_name = 'Yvan Tellez' WHERE LOWER(email) = 'yvan.tellez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Edwin', last_name = 'Tellez', display_name = 'Edwin Tellez' WHERE LOWER(email) = 'edwintellez1231@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gregory', last_name = 'Stanford', display_name = 'Gregory Stanford' WHERE LOWER(email) = 'gregory.stanford@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Osvaldo', last_name = 'Soto Macedo', display_name = 'Osvaldo Soto Macedo' WHERE LOWER(email) = 'osvaldo.macedo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Isaias', last_name = 'Shaw Gomez', display_name = 'Isaias Shaw Gomez' WHERE LOWER(email) = 'isaiasgom120@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Shaw', display_name = 'Michael Shaw' WHERE LOWER(email) = '19michaelshaw@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Adiel', last_name = 'Sanchez Alvarenga', display_name = 'Adiel Sanchez Alvarenga' WHERE LOWER(email) = 'adiel.sanchez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cristian', last_name = 'Sanchez', display_name = 'Cristian Sanchez' WHERE LOWER(email) = 'csanchezz1@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kevin', last_name = 'Salvador-Mena', display_name = 'Kevin Salvador-Mena' WHERE LOWER(email) = 'kevinsalvador1111@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Rumbo Hernandez', display_name = 'Jose Rumbo Hernandez' WHERE LOWER(email) = 'mariokid18@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Isaac', last_name = 'Rombach', display_name = 'Isaac Rombach' WHERE LOWER(email) = 'icr252@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Juan', last_name = 'Rodriguez Mata', display_name = 'Juan Rodriguez Mata' WHERE LOWER(email) = 'juan.mata@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cesar', last_name = 'Molina-Barcenas', display_name = 'Cesar Molina-Barcenas' WHERE LOWER(email) = 'cesar.molina@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joshua', last_name = 'Miller', display_name = 'Joshua Miller' WHERE LOWER(email) = 'joshua.d.miller236@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joseph', last_name = 'Leonelli', display_name = 'Joseph Leonelli' WHERE LOWER(email) = 'leonelli_jr@yahoo.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Eric', last_name = 'Juarez', display_name = 'Eric Juarez' WHERE LOWER(email) = 'juarezeric896@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sonny', last_name = 'Joyner', display_name = 'Sonny Joyner' WHERE LOWER(email) = 'sonny.joyner@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hunter', last_name = 'Hinson', display_name = 'Hunter Hinson' WHERE LOWER(email) = 'hunter.hinson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Osmer', last_name = 'Gutierrez', display_name = 'Osmer Gutierrez' WHERE LOWER(email) = 'osmer.gutierrez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sergio', last_name = 'Gonzalez', display_name = 'Sergio Gonzalez' WHERE LOWER(email) = 'gonzalezs129@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Dominique', last_name = 'Gladden', display_name = 'Dominique Gladden' WHERE LOWER(email) = 'gladdendomo93@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brandon', last_name = 'Garcia-Martinez', display_name = 'Brandon Garcia-Martinez' WHERE LOWER(email) = 'brandon.garcia@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gualberto', last_name = 'Chinchilla', display_name = 'Gualberto Chinchilla' WHERE LOWER(email) = 'alonzogarcia1398@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Austin', last_name = 'Beachum', display_name = 'Austin Beachum' WHERE LOWER(email) = 'austin.beachum@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Zachary', last_name = 'Bailey', display_name = 'Zachary Bailey' WHERE LOWER(email) = 'zackbailey034@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Marlon', last_name = 'Baez-Huerta', display_name = 'Marlon Baez-Huerta' WHERE LOWER(email) = 'marlonbaez1@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Lenin', last_name = 'Arteaga', display_name = 'Lenin Arteaga' WHERE LOWER(email) = 'lenin.arteaga06@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Alvarez Rios', display_name = 'Jose Alvarez Rios' WHERE LOWER(email) = 'jose.alvarez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Gutierrez', display_name = 'Jose Gutierrez' WHERE LOWER(email) = 'gutierrez.jose6894@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Omar', last_name = 'Mojica Valencia', display_name = 'Omar Mojica Valencia' WHERE LOWER(email) = 'mojicaomar26@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jonathan', last_name = 'Amezquita', display_name = 'Jonathan Amezquita' WHERE LOWER(email) = 'jamezqu01@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Victor', last_name = 'Aleman Osorio', display_name = 'Victor Aleman Osorio' WHERE LOWER(email) = 'lesviaa@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hernesto', last_name = 'Castrejon', display_name = 'Hernesto Castrejon' WHERE LOWER(email) = 'ssoccer355@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Benito', last_name = 'Garcia', display_name = 'Benito Garcia' WHERE LOWER(email) = 'benitogarciaa14@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Darwin', last_name = 'Padilla Rodriguez', display_name = 'Darwin Padilla Rodriguez' WHERE LOWER(email) = 'darlinrodriguez0101@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Devin', last_name = 'Harvey', display_name = 'Devin Harvey' WHERE LOWER(email) = 'devin.harvey@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jesus', last_name = 'Silva Caballero', display_name = 'Jesus Silva Caballero' WHERE LOWER(email) = 'jjsc704@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brian', last_name = 'Wilson', display_name = 'Brian Wilson' WHERE LOWER(email) = 'brian.wilson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Benjamin', last_name = 'Sergeant', display_name = 'Benjamin Sergeant' WHERE LOWER(email) = 'benlsergeant@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Guzman', display_name = 'Matthew Guzman' WHERE LOWER(email) = 'mman7777@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Aidan', last_name = 'Reynolds', display_name = 'Aidan Reynolds' WHERE LOWER(email) = 'aidan.reynolds36@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hector', last_name = 'Villatoro', display_name = 'Hector Villatoro' WHERE LOWER(email) = 'hector.villatoro@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Richard', last_name = 'Valverde', display_name = 'Richard Valverde' WHERE LOWER(email) = 'richard.valverde@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jack', last_name = 'Tuck', display_name = 'Jack Tuck' WHERE LOWER(email) = 'jack.tuck@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Petty', display_name = 'Michael Petty' WHERE LOWER(email) = 'mike.petty@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Dustin', last_name = 'Mcniff', display_name = 'Dustin Mcniff' WHERE LOWER(email) = 'dustin.mcniff@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Casey', last_name = 'Johnson', display_name = 'Casey Johnson' WHERE LOWER(email) = 'casey.johnson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Eric', last_name = 'Wilson', display_name = 'Eric Wilson' WHERE LOWER(email) = 'travis.wilson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Todd', last_name = 'Regis', display_name = 'Todd Regis' WHERE LOWER(email) = 'todd.regis@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'William', last_name = 'Porter', display_name = 'William Porter' WHERE LOWER(email) = 'treyporter3@yahoo.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Donny', last_name = 'Petty', display_name = 'Donny Petty' WHERE LOWER(email) = 'donny.petty@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jonathon', last_name = 'Mckay', display_name = 'Jonathon Mckay' WHERE LOWER(email) = 'jonathon.mckay@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Christopher', last_name = 'Kluttz', display_name = 'Christopher Kluttz' WHERE LOWER(email) = 'chris.kluttz@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gary', last_name = 'Gaylor', display_name = 'Gary Gaylor' WHERE LOWER(email) = 'gary.gaylor@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Roberto', last_name = 'Gabarrete', display_name = 'Roberto Gabarrete' WHERE LOWER(email) = 'roberto.gabarrete@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Bryson', last_name = 'Cowart', display_name = 'Bryson Cowart' WHERE LOWER(email) = 'bryson.cowart@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brandon', last_name = 'Collins', display_name = 'Brandon Collins' WHERE LOWER(email) = 'brandon.collins@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Baldwin', display_name = 'Michael Baldwin' WHERE LOWER(email) = 'michael.baldwin@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Austin', last_name = 'Anderson', display_name = 'Austin Anderson' WHERE LOWER(email) = 'austin.anderson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'William', last_name = 'Powell', display_name = 'William Powell' WHERE LOWER(email) = 'william.powell@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jesus', last_name = 'Diaz Hernandez', display_name = 'Jesus Diaz Hernandez' WHERE LOWER(email) = 'jesus.hernandez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Gutierrez', display_name = 'Matthew Gutierrez' WHERE LOWER(email) = 'matthew.gutierrez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Christopher', last_name = 'Meek', display_name = 'Christopher Meek' WHERE LOWER(email) = 'christopher.meek@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Robert', last_name = 'Styers', display_name = 'Robert Styers' WHERE LOWER(email) = 'tony.styers@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jason', last_name = 'Turner', display_name = 'Jason Turner' WHERE LOWER(email) = 'jason.turner@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Celena', last_name = 'White', display_name = 'Celena White' WHERE LOWER(email) = 'celena.white@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Stancil', display_name = 'Matthew Stancil' WHERE LOWER(email) = 'matthew.stancil@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Green', display_name = 'Michael Green' WHERE LOWER(email) = 'michael.green@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Alan', last_name = 'Caldwell', display_name = 'Alan Caldwell' WHERE LOWER(email) = 'alan.caldwell@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Aleah', last_name = 'Wheeler', display_name = 'Aleah Wheeler' WHERE LOWER(email) = 'aleah.wheeler@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Crystal', last_name = 'Wallace', display_name = 'Crystal Wallace' WHERE LOWER(email) = 'crystal.wallace@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Andrew', last_name = 'Stancil', display_name = 'Andrew Stancil' WHERE LOWER(email) = 'andrew.stancil@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jessica', last_name = 'Phifer', display_name = 'Jessica Phifer' WHERE LOWER(email) = 'jessica.phifer@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rusty', last_name = 'Norris', display_name = 'Rusty Norris' WHERE LOWER(email) = 'rusty.norris@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Skylar', last_name = 'Morgan', display_name = 'Skylar Morgan' WHERE LOWER(email) = 'skylar.morgan@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Thomas', last_name = 'Lloyd', display_name = 'Thomas Lloyd' WHERE LOWER(email) = 'nathan.lloyd@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Leonard', last_name = 'Leroux', display_name = 'Leonard Leroux' WHERE LOWER(email) = 'doug.leroux@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'William', last_name = 'Jones', display_name = 'William Jones' WHERE LOWER(email) = 'will.jones@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Bailey', last_name = 'Jackson', display_name = 'Bailey Jackson' WHERE LOWER(email) = 'bailey.jackson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Erik', last_name = 'Gelardi', display_name = 'Erik Gelardi' WHERE LOWER(email) = 'erik.gelardi@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Marie', last_name = 'Galioto', display_name = 'Marie Galioto' WHERE LOWER(email) = 'marie.galioto@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Angela', last_name = 'Chunn', display_name = 'Angela Chunn' WHERE LOWER(email) = 'angela.chunn@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Shannon', last_name = 'Cheeks', display_name = 'Shannon Cheeks' WHERE LOWER(email) = 'shannon.cheeks@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sydney', last_name = 'Busch', display_name = 'Sydney Busch' WHERE LOWER(email) = 'sydney.busch@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Paul', last_name = 'Ward', display_name = 'Paul Ward' WHERE LOWER(email) = 'paul.ward@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Stephanie', last_name = 'Czechowicz', display_name = 'Stephanie Czechowicz' WHERE LOWER(email) = 'smczechowicz@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Thomas', last_name = 'Stubbs', display_name = 'Thomas Stubbs' WHERE LOWER(email) = 'thomas.stubbs@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Katherine', last_name = 'Miller', display_name = 'Katherine Miller' WHERE LOWER(email) = 'katie.miller@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Micah', last_name = 'Partlow', display_name = 'Micah Partlow' WHERE LOWER(email) = 'micah.partlow@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mary', last_name = 'Rochin', display_name = 'Mary Rochin' WHERE LOWER(email) = 'susie.rochin@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gregory', last_name = 'Lipa', display_name = 'Gregory Lipa' WHERE LOWER(email) = 'greg.lipa@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Miguel', last_name = 'Morales', display_name = 'Miguel Morales' WHERE LOWER(email) = 'miguel.morales@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rebekah', last_name = 'Buchanan', display_name = 'Rebekah Buchanan' WHERE LOWER(email) = 'rebekah.buchanan@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rayann', last_name = 'Lefever', display_name = 'Rayann Lefever' WHERE LOWER(email) = 'rayann.lefever@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rebecca', last_name = 'Guiler', display_name = 'Rebecca Guiler' WHERE LOWER(email) = 'rebecca.guiler@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Lee', display_name = 'Michael Lee' WHERE LOWER(email) = 'michael.lee@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Alexander', last_name = 'Houseal', display_name = 'Alexander Houseal' WHERE LOWER(email) = 'alexander.houseal@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Scarlett', last_name = 'Bowman', display_name = 'Scarlett Bowman' WHERE LOWER(email) = 'scarlett.bowman@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nicholas', last_name = 'Holesa', display_name = 'Nicholas Holesa' WHERE LOWER(email) = 'nicholas.holesa@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Claudia', last_name = 'Finley', display_name = 'Claudia Finley' WHERE LOWER(email) = 'claudia.finley@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nicholas', last_name = 'Barbee', display_name = 'Nicholas Barbee' WHERE LOWER(email) = 'nicholas.barbee@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Conner', last_name = 'Tuck', display_name = 'Conner Tuck' WHERE LOWER(email) = 'conner.tuck@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Christopher', last_name = 'Rayfield', display_name = 'Christopher Rayfield' WHERE LOWER(email) = 'dusty.rayfield@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Nolen', display_name = 'Michael Nolen' WHERE LOWER(email) = 'blair.nolen@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Justin', last_name = 'Hawkins', display_name = 'Justin Hawkins' WHERE LOWER(email) = 'jgould441@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jimmy', last_name = 'Duncan', display_name = 'Jimmy Duncan' WHERE LOWER(email) = 'lachay.duncan@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jacob', last_name = 'Villatoro', display_name = 'Jacob Villatoro' WHERE LOWER(email) = 'jacob101998@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Juan', last_name = 'Ventura Ruiz', display_name = 'Juan Ventura Ruiz' WHERE LOWER(email) = 'lovermachine2013@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jonathan', last_name = 'Thompson', display_name = 'Jonathan Thompson' WHERE LOWER(email) = 'jonathan.thompson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kyle', last_name = 'Spencer', display_name = 'Kyle Spencer' WHERE LOWER(email) = 'kylespencer024@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Christopher', last_name = 'Richards', display_name = 'Christopher Richards' WHERE LOWER(email) = 'david.richards@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Eric', last_name = 'Ramos', display_name = 'Eric Ramos' WHERE LOWER(email) = 'ericramos167@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Austin', last_name = 'Nolen', display_name = 'Austin Nolen' WHERE LOWER(email) = 'austin.nolen@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Robert', last_name = 'Nolen', display_name = 'Robert Nolen' WHERE LOWER(email) = 'nolenjr413@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Dylan', last_name = 'Neagle', display_name = 'Dylan Neagle' WHERE LOWER(email) = 'dylan.neagle2001@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Moss', display_name = 'Matthew Moss' WHERE LOWER(email) = 'matt.moss@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Menjay', last_name = 'Melsior', display_name = 'Menjay Melsior' WHERE LOWER(email) = 'menjay.melsior@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kaiser', last_name = 'Kayton', display_name = 'Kaiser Kayton' WHERE LOWER(email) = 'kaiser.kayton@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jalen', last_name = 'Ingram', display_name = 'Jalen Ingram' WHERE LOWER(email) = 'jaleningram72@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brandon', last_name = 'Hall', display_name = 'Brandon Hall' WHERE LOWER(email) = 'brandon.hall@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jason', last_name = 'Hall', display_name = 'Jason Hall' WHERE LOWER(email) = 'jason.hall@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Miguel', last_name = 'Garcia Baker', display_name = 'Miguel Garcia Baker' WHERE LOWER(email) = 'miguel.baker@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jared', last_name = 'Collins', display_name = 'Jared Collins' WHERE LOWER(email) = 'jarad.collins@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Frederick', last_name = 'Black', display_name = 'Frederick Black' WHERE LOWER(email) = 'frederick.black@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Steven', last_name = 'Bainbridge', display_name = 'Steven Bainbridge' WHERE LOWER(email) = 'mtthwbainbridge@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'James', last_name = 'Anderson', display_name = 'James Anderson' WHERE LOWER(email) = 'jamesdanderson04@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Justin', last_name = 'Morris', display_name = 'Justin Morris' WHERE LOWER(email) = 'justinmorris337@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Lyndon', last_name = 'Alejo', display_name = 'Lyndon Alejo' WHERE LOWER(email) = 'alejo2000@bellsouth.net' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Timothy', last_name = 'Dixon', display_name = 'Timothy Dixon' WHERE LOWER(email) = 'timdixon4408@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Benjamin', last_name = 'Self', display_name = 'Benjamin Self' WHERE LOWER(email) = 'benself1998@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Darian', last_name = 'Massey', display_name = 'Darian Massey' WHERE LOWER(email) = 'darianmassey10@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'James', last_name = 'Hudson', display_name = 'James Hudson' WHERE LOWER(email) = 'jhudson12356@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'David', last_name = 'Castro', display_name = 'David Castro' WHERE LOWER(email) = 'david.castro@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jacob', last_name = 'Nix', display_name = 'Jacob Nix' WHERE LOWER(email) = 'jacobnix1@icloud.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hunter', last_name = 'Donaldson', display_name = 'Hunter Donaldson' WHERE LOWER(email) = 'th3d1rtyk0b0ld@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Morales', display_name = 'Jose Morales' WHERE LOWER(email) = 'jm867331@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Andrew', last_name = 'Fisher', display_name = 'Andrew Fisher' WHERE LOWER(email) = 'afisher5544@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Clinton', last_name = 'Yost', display_name = 'Clinton Yost' WHERE LOWER(email) = 'clinton.yost@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mycal', last_name = 'Self', display_name = 'Mycal Self' WHERE LOWER(email) = 'jasonhailey0709@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Dustin', last_name = 'Barnes', display_name = 'Dustin Barnes' WHERE LOWER(email) = 'seeyanc@outlook.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Damien', last_name = 'Elkovich', display_name = 'Damien Elkovich' WHERE LOWER(email) = 'elkovichd00@yahoo.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jorge', last_name = 'Bermudez', display_name = 'Jorge Bermudez' WHERE LOWER(email) = 'lovejumex730@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Victor', last_name = 'Pierce', display_name = 'Victor Pierce' WHERE LOWER(email) = 'victorpierce21b.o.s@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Karl', last_name = 'Kimbrell', display_name = 'Karl Kimbrell' WHERE LOWER(email) = 'karl.kimbrell@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hector', last_name = 'Vasquez', display_name = 'Hector Vasquez' WHERE LOWER(email) = 'hector.vasquez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Edwin', last_name = 'Sevilla Lagos', display_name = 'Edwin Sevilla Lagos' WHERE LOWER(email) = 'alex.sevilla@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cristian', last_name = 'Rodriguez', display_name = 'Cristian Rodriguez' WHERE LOWER(email) = 'cristian.rodriguez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rodrigo', last_name = 'Merida', display_name = 'Rodrigo Merida' WHERE LOWER(email) = 'rodrigo.merida@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Alexis', last_name = 'Guzman', display_name = 'Alexis Guzman' WHERE LOWER(email) = 'alexis.guzman@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Gallego', display_name = 'Michael Gallego' WHERE LOWER(email) = 'michael.gallego@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Yanet', last_name = 'Chona Montes', display_name = 'Yanet Chona Montes' WHERE LOWER(email) = 'yanet.chona@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sebastian', last_name = 'Carrillo Castillo', display_name = 'Sebastian Carrillo Castillo' WHERE LOWER(email) = 'sebastian.carrillo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Susan', last_name = 'Bennett', display_name = 'Susan Bennett' WHERE LOWER(email) = 'sue.bennett@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Carlos', last_name = 'Sosa Rodriguez', display_name = 'Carlos Sosa Rodriguez' WHERE LOWER(email) = 'marysosa261@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jacqueline', last_name = 'Sigerist', display_name = 'Jacqueline Sigerist' WHERE LOWER(email) = 'jacque.sigerist@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Carlos', last_name = 'Santizo', display_name = 'Carlos Santizo' WHERE LOWER(email) = 'carlos.santizo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Herson', last_name = 'Sanchez', display_name = 'Herson Sanchez' WHERE LOWER(email) = 'herson.sanchez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Ana', last_name = 'Ruiz', display_name = 'Ana Ruiz' WHERE LOWER(email) = 'ana3611ruiz@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Rojas', display_name = 'Jose Rojas' WHERE LOWER(email) = 'sendymartinez89@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gabriel', last_name = 'Robledo', display_name = 'Gabriel Robledo' WHERE LOWER(email) = 'gabe.robledo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cristobal', last_name = 'Moyado', display_name = 'Cristobal Moyado' WHERE LOWER(email) = 'moyadoimi@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Eduardo', last_name = 'Moyado', display_name = 'Eduardo Moyado' WHERE LOWER(email) = 'eduardogallardo040@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Leslye', last_name = 'Mosquera', display_name = 'Leslye Mosquera' WHERE LOWER(email) = 'stancil.bsa12@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Salomon', last_name = 'Moctezuma Castillo', display_name = 'Salomon Moctezuma Castillo' WHERE LOWER(email) = 'salomon.moctezuma@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jodi', last_name = 'Gaddy', display_name = 'Jodi Gaddy' WHERE LOWER(email) = 'jodi.gaddy@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gissell', last_name = 'Flores', display_name = 'Gissell Flores' WHERE LOWER(email) = 'gissell.flores@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cristopher', last_name = 'Flores', display_name = 'Cristopher Flores' WHERE LOWER(email) = 'cristopherf594@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jamaal', last_name = 'Bracey', display_name = 'Jamaal Bracey' WHERE LOWER(email) = 'jamaal.bracey@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Josue', last_name = 'Mata', display_name = 'Josue Mata' WHERE LOWER(email) = 'josue.mata@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jordan', last_name = 'Gaddy', display_name = 'Jordan Gaddy' WHERE LOWER(email) = 'jordan.gaddy@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Gabriel', last_name = 'Jordao', display_name = 'Gabriel Jordao' WHERE LOWER(email) = 'gabriel.jordao@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Elisabeth', last_name = 'Perrigo', display_name = 'Elisabeth Perrigo' WHERE LOWER(email) = 'elisabeth.perrigo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Houser', display_name = 'Michael Houser' WHERE LOWER(email) = 'scott.houser@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Keelin', last_name = 'Stockwell', display_name = 'Keelin Stockwell' WHERE LOWER(email) = 'keelin.stockwell@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Stephanie', last_name = 'Buono', display_name = 'Stephanie Buono' WHERE LOWER(email) = 'stephanie.buono@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sthephanie', last_name = 'Carrillo Castillo', display_name = 'Sthephanie Carrillo Castillo' WHERE LOWER(email) = 'sthephanie.castillo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Henry', last_name = 'Andrades', display_name = 'Henry Andrades' WHERE LOWER(email) = 'henry.andrades@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nicholas', last_name = 'Trei', display_name = 'Nicholas Trei' WHERE LOWER(email) = 'nicholas.trei@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Galo', last_name = 'Samaniego', display_name = 'Galo Samaniego' WHERE LOWER(email) = 'galo.samaniego@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Robin', last_name = 'White', display_name = 'Robin White' WHERE LOWER(email) = 'robin.white@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Oscar', last_name = 'Cedillos', display_name = 'Oscar Cedillos' WHERE LOWER(email) = 'eduardochavez141088@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Karen', last_name = 'Cano Urrutia', display_name = 'Karen Cano Urrutia' WHERE LOWER(email) = 'andreacano1418@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jareth', last_name = 'Gonzales', display_name = 'Jareth Gonzales' WHERE LOWER(email) = 'nazaluna18@hotmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Bradley', last_name = 'Robinson', display_name = 'Bradley Robinson' WHERE LOWER(email) = 'brad.robinson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Trystan', last_name = 'Jones', display_name = 'Trystan Jones' WHERE LOWER(email) = 'trystan.jones@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Manuel', last_name = 'Hernandez', display_name = 'Manuel Hernandez' WHERE LOWER(email) = 'manuel.hernandez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'John', last_name = 'Flanagan', display_name = 'John Flanagan' WHERE LOWER(email) = 'jd.flanagan@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kathleen', last_name = 'Brumagim', display_name = 'Kathleen Brumagim' WHERE LOWER(email) = 'kathleen.brumagim@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Melvin', last_name = 'Avalos', display_name = 'Melvin Avalos' WHERE LOWER(email) = 'melvin.avalos@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Ryan', last_name = 'Saunders', display_name = 'Ryan Saunders' WHERE LOWER(email) = 'ryan.saunders@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Dylan', last_name = 'Hahn', display_name = 'Dylan Hahn' WHERE LOWER(email) = 'dylan.hahn@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Edwar', last_name = 'Cayetano Norales', display_name = 'Edwar Cayetano Norales' WHERE LOWER(email) = 'edwardnorales@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Morgan', last_name = 'Whittington', display_name = 'Morgan Whittington' WHERE LOWER(email) = 'morgan.whittington@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Ryan', last_name = 'Meckler', display_name = 'Ryan Meckler' WHERE LOWER(email) = 'ryan.meckler@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brian', last_name = 'Becker', display_name = 'Brian Becker' WHERE LOWER(email) = 'brian.becker@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Eric', last_name = 'Hunt', display_name = 'Eric Hunt' WHERE LOWER(email) = 'eric.hunt@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Alex', last_name = 'Holman', display_name = 'Alex Holman' WHERE LOWER(email) = 'alex.holman@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hope', last_name = 'Krekoska', display_name = 'Hope Krekoska' WHERE LOWER(email) = 'hope.krekoska@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Luis Alberto', last_name = 'Reyes Hernandez', display_name = 'Luis Alberto Reyes Hernandez' WHERE LOWER(email) = 'luis.reyes@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'James', last_name = 'Hoover', display_name = 'James Hoover' WHERE LOWER(email) = 'jamie.hoover@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'John', last_name = 'Graham', display_name = 'John Graham' WHERE LOWER(email) = 'jbgpainter1@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Lawrence', last_name = 'Beardsley', display_name = 'Lawrence Beardsley' WHERE LOWER(email) = 'pappyray883@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Victoria', last_name = 'Reiner', display_name = 'Victoria Reiner' WHERE LOWER(email) = 'victoria.reiner@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Darwin', last_name = 'Portillo Beltran', display_name = 'Darwin Portillo Beltran' WHERE LOWER(email) = 'beltrandarwin59@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Kline', display_name = 'Matthew Kline' WHERE LOWER(email) = 'shane.kline@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mason', last_name = 'Gregory', display_name = 'Mason Gregory' WHERE LOWER(email) = 'mason.gregory@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Juan', last_name = 'Dinarte', display_name = 'Juan Dinarte' WHERE LOWER(email) = 'dinartejuancarlos1@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Danilo', last_name = 'Conejo', display_name = 'Danilo Conejo' WHERE LOWER(email) = 'drabitjr22@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kyle', last_name = 'Barrow', display_name = 'Kyle Barrow' WHERE LOWER(email) = 'kyle.barrow@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jaime', last_name = 'Woods', display_name = 'Jaime Woods' WHERE LOWER(email) = 'jaime.woods@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Leonardo', last_name = 'Santos', display_name = 'Leonardo Santos' WHERE LOWER(email) = 'leonardo.kushimizo@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Melissa', last_name = 'Nash', display_name = 'Melissa Nash' WHERE LOWER(email) = 'melissa.nash@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'William', last_name = 'Sims', display_name = 'William Sims' WHERE LOWER(email) = 'mike.sims@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Carla', last_name = 'Santos Reyes', display_name = 'Carla Santos Reyes' WHERE LOWER(email) = 'lolamike2024@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Devin', last_name = 'Simpson', display_name = 'Devin Simpson' WHERE LOWER(email) = 'devin.simpson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joe', last_name = 'Barkowski', display_name = 'Joe Barkowski' WHERE LOWER(email) = 'joe.barkowski@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jesus', last_name = 'Vazquez', display_name = 'Jesus Vazquez' WHERE LOWER(email) = 'jesus_704@live.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Emanuel', last_name = 'Rodriguez', display_name = 'Emanuel Rodriguez' WHERE LOWER(email) = 'manny@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Steven', last_name = 'Linker', display_name = 'Steven Linker' WHERE LOWER(email) = 'chad.linker@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'David Jaimes', last_name = 'Gorostieta', display_name = 'David Jaimes Gorostieta' WHERE LOWER(email) = 'david.jaimes@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jesus', last_name = 'Diaz Caspeta', display_name = 'Jesus Diaz Caspeta' WHERE LOWER(email) = 'jesus.diaz@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Brandon', last_name = 'Borleis', display_name = 'Brandon Borleis' WHERE LOWER(email) = 'brandon.borleis@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Braxton', last_name = 'Tooke', display_name = 'Braxton Tooke' WHERE LOWER(email) = 'braxton.tooke@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Sidney', last_name = 'San', display_name = 'Sidney San' WHERE LOWER(email) = 'sidney.san@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Yoni', last_name = 'Leon', display_name = 'Yoni Leon' WHERE LOWER(email) = 'yoni.leon@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Enrique', last_name = 'Gomez', display_name = 'Enrique Gomez' WHERE LOWER(email) = 'efg3981@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Maria', last_name = 'Flores', display_name = 'Maria Flores' WHERE LOWER(email) = 'maria.flores@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Deshawn', last_name = 'Daniels', display_name = 'Deshawn Daniels' WHERE LOWER(email) = 'deshawn.daniels@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Richard', last_name = 'Cordero', display_name = 'Richard Cordero' WHERE LOWER(email) = 'richardadriancordero@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Wilfredo', last_name = 'Briones', display_name = 'Wilfredo Briones' WHERE LOWER(email) = 'wilfredo.briones@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Charles', last_name = 'Reeve', display_name = 'Charles Reeve' WHERE LOWER(email) = 'charlie.reeve@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Hunter', display_name = 'Matthew Hunter' WHERE LOWER(email) = 'matthew.hunter@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Luis', last_name = 'Gomez Hidalgo', display_name = 'Luis Gomez Hidalgo' WHERE LOWER(email) = 'luisgomez70491@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Paul', last_name = 'Denino', display_name = 'Paul Denino' WHERE LOWER(email) = 'paul.denino@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Oswaldo', last_name = 'Schott', display_name = 'Oswaldo Schott' WHERE LOWER(email) = 'oswaldo.schott@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joel', last_name = 'Rubio Santos', display_name = 'Joel Rubio Santos' WHERE LOWER(email) = 'alex.santos01990@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Rumbo', display_name = 'Jose Rumbo' WHERE LOWER(email) = 'jose.rumbo@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mayra', last_name = 'Martinez', display_name = 'Mayra Martinez' WHERE LOWER(email) = 'mayra.martinez@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joseph', last_name = 'Galioto', display_name = 'Joseph Galioto' WHERE LOWER(email) = 'joe.galioto@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Noe', last_name = 'Jacobo Vazquez', display_name = 'Noe Jacobo Vazquez' WHERE LOWER(email) = 'jacobo3043@yahoo.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jose', last_name = 'Garcia Menjivar', display_name = 'Jose Garcia Menjivar' WHERE LOWER(email) = 'daniel.garcia@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nicholas', last_name = 'Andrades', display_name = 'Nicholas Andrades' WHERE LOWER(email) = 'nalexander1526@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Winnifred', last_name = 'Helstone', display_name = 'Winnifred Helstone' WHERE LOWER(email) = 'winnifred.helstone@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Amber', last_name = 'Widenhouse', display_name = 'Amber Widenhouse' WHERE LOWER(email) = 'amber.widenhouse@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Scott', last_name = 'Stancil', display_name = 'Scott Stancil' WHERE LOWER(email) = 'scott.stancil@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Matthew', last_name = 'Mercer', display_name = 'Matthew Mercer' WHERE LOWER(email) = 'matt.mercer@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Scottie', last_name = 'Kimble', display_name = 'Scottie Kimble' WHERE LOWER(email) = 'scottie.kimble@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jennifer', last_name = 'Burleson', display_name = 'Jennifer Burleson' WHERE LOWER(email) = 'jenny.burleson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Shana', last_name = 'Woolard', display_name = 'Shana Woolard' WHERE LOWER(email) = 'shana.woolard@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Andrew', last_name = 'Szafranski', display_name = 'Andrew Szafranski' WHERE LOWER(email) = 'andrew.szafranski@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Cynthia', last_name = 'Stubbs', display_name = 'Cynthia Stubbs' WHERE LOWER(email) = 'cynthia.stubbs@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Justin', last_name = 'Safrit', display_name = 'Justin Safrit' WHERE LOWER(email) = 'justin.safrit@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Anthony', last_name = 'Romero', display_name = 'Anthony Romero' WHERE LOWER(email) = 'anthony.romero@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Marlana', last_name = 'Perry', display_name = 'Marlana Perry' WHERE LOWER(email) = 'marlana.perry@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'James', last_name = 'Miller', display_name = 'James Miller' WHERE LOWER(email) = 'james.miller@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Joseph', last_name = 'Mangum', display_name = 'Joseph Mangum' WHERE LOWER(email) = 'brian.mangum@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kimberly', last_name = 'Carey', display_name = 'Kimberly Carey' WHERE LOWER(email) = 'kim.carey@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Aleah', last_name = 'Holland', display_name = 'Aleah Holland' WHERE LOWER(email) = 'aleah.holland@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Anjannette', last_name = 'Hinson', display_name = 'Anjannette Hinson' WHERE LOWER(email) = 'anjie.hinson@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jason', last_name = 'Gillispie', display_name = 'Jason Gillispie' WHERE LOWER(email) = 'jason.gillispie@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Davis', display_name = 'Michael Davis' WHERE LOWER(email) = 'mike.davis@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Angela', last_name = 'Black', display_name = 'Angela Black' WHERE LOWER(email) = 'angela.black@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Hannah', last_name = 'Bacon', display_name = 'Hannah Bacon' WHERE LOWER(email) = 'maggie.bacon@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Roberto', last_name = 'Vergara', display_name = 'Roberto Vergara' WHERE LOWER(email) = 'carlos.vergara@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Kristine', last_name = 'Gunther', display_name = 'Kristine Gunther' WHERE LOWER(email) = 'kris.gunther@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Douglas', last_name = 'Jones', display_name = 'Douglas Jones' WHERE LOWER(email) = 'doug.jones@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Angel', last_name = 'Morales Francisco', display_name = 'Angel Morales Francisco' WHERE LOWER(email) = 'angel.morales@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nathaniel', last_name = 'Miller', display_name = 'Nathaniel Miller' WHERE LOWER(email) = 'howitzer1911@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Daniel', last_name = 'Orozco', display_name = 'Daniel Orozco' WHERE LOWER(email) = 'daniel.orozco@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'James', last_name = 'Barker', display_name = 'James Barker' WHERE LOWER(email) = 'wayne.barker@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jon', last_name = 'Thomas', display_name = 'Jon Thomas' WHERE LOWER(email) = 'jon.thomas@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Fouleh', last_name = 'Freitekh', display_name = 'Fouleh Freitekh' WHERE LOWER(email) = 'fouleh.freitekh@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Rachel', last_name = 'Valle', display_name = 'Rachel Valle' WHERE LOWER(email) = 'rachel.valle@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'David', last_name = 'Ruiz Dela Pena', display_name = 'David Ruiz Dela Pena' WHERE LOWER(email) = 'david.ruiz@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Bryan', last_name = 'Thomas', display_name = 'Bryan Thomas' WHERE LOWER(email) = 'bryan.thomas@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Anthony', last_name = 'Foster', display_name = 'Anthony Foster' WHERE LOWER(email) = 'anthony.foster@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'William', last_name = 'Dozier', display_name = 'William Dozier' WHERE LOWER(email) = 'doug.dozier@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Robert', last_name = 'Mceachern', display_name = 'Robert Mceachern' WHERE LOWER(email) = 'robert.mceachern@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Craig', last_name = 'Neal', display_name = 'Craig Neal' WHERE LOWER(email) = 'craig.neal@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Steven', last_name = 'Benesh', display_name = 'Steven Benesh' WHERE LOWER(email) = 'steven.benesh@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Tara', last_name = 'White', display_name = 'Tara White' WHERE LOWER(email) = 'tara.white@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Emily', last_name = 'Messina', display_name = 'Emily Messina' WHERE LOWER(email) = 'emily.messina@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Christopher', last_name = 'Kostrab', display_name = 'Christopher Kostrab' WHERE LOWER(email) = 'chris.kostrab@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Michael', last_name = 'Besserdich', display_name = 'Michael Besserdich' WHERE LOWER(email) = 'allen.besserdich@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Nikolai', last_name = 'Fulbright', display_name = 'Nikolai Fulbright' WHERE LOWER(email) = 'nikolaifulbright7@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Oscar', last_name = 'Amezquita', display_name = 'Oscar Amezquita' WHERE LOWER(email) = 'oscaralonso423@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Benjamin', last_name = 'Russey', display_name = 'Benjamin Russey' WHERE LOWER(email) = 'benjaminrussey@yahoo.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Paul', last_name = 'Welling', display_name = 'Paul Welling' WHERE LOWER(email) = 'paulwellig13@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Henry', last_name = 'Shepherd', display_name = 'Henry Shepherd' WHERE LOWER(email) = 'henry.shepherd@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Aydan', last_name = 'Patterson', display_name = 'Aydan Patterson' WHERE LOWER(email) = 'aydanpatterson10@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jesus', last_name = 'Dorta', display_name = 'Jesus Dorta' WHERE LOWER(email) = 'jesus.dorta@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jacob', last_name = 'Beck', display_name = 'Jacob Beck' WHERE LOWER(email) = 'jake.beck@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Jacob', last_name = 'Hord', display_name = 'Jacob Hord' WHERE LOWER(email) = 'jakehord16@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'David', last_name = 'Presley', display_name = 'David Presley' WHERE LOWER(email) = 'wayne.presley@stancilservices.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Grant', last_name = 'Robbins', display_name = 'Grant Robbins' WHERE LOWER(email) = 'ftwgrizzy@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mark', last_name = 'Gutierrez', display_name = 'Mark Gutierrez' WHERE LOWER(email) = 'gutierrezmark462@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Mariano', last_name = 'Lopez', display_name = 'Mariano Lopez' WHERE LOWER(email) = 'lopezmariano40@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Felipe', last_name = 'Moreno', display_name = 'Felipe Moreno' WHERE LOWER(email) = 'fm537122@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
UPDATE profiles SET first_name = 'Terrance', last_name = 'Woods', display_name = 'Terrance Woods' WHERE LOWER(email) = 'nmw22boi@gmail.com' AND (first_name IS NULL OR last_name IS NULL);
